[package]
authors = ["Messense Lv <messense@icloud.com>"]
name = "word-count"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.0.2"

[dependencies.pyo3]
pyo3 = "0.12.4"
features = ["extension-module"]


[lib]
name = "word_count"
crate-type = ["cdylib"]
